version: "3.9"
services:
  web:
    build: ./
    ports:
      - "3000:3000"
    links:
      - mongodb
    environment:
      - DB_HOST=mongodb:27017
  mongodb:
    build: ./db_dockerfile
    container_name: node-db
    ports:
      - "27017:27017"
